# specify version
version: '3.8'

# two services
services:
  # service 1 - agent
  agent:
    # build the Dockerfile in the same folder
    build: .
    env_file:
      - .env

  # service 2 - dynamoDB
