# specify version
version: '3.8'

# specify services
services:
  agent:
    #image name
    image: nnguyen6/agent:1.0
    # build the Dockerfile
    build:
      ## Specify context
      context: .
      ## args only active during build time, can't be accessed during run time
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        REGION: ${REGION}
    # environments
    env_file:
      - .env
    environment:
      APP_MODE: release
